replicaCount: 1

image:
  repository: abhisheksdtu/golimiter
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

redis:
  enabled: true
  port: 6379
  image: redis:7-alpine

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
